spring.application.name=RateLimiter

resilience4j.ratelimiter.instances.serviceBRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.serviceBRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.serviceBRateLimiter.timeout-duration=0
