server.port=8082

spring.application.name=login-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-login:3306/logindb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:ArNAZeN3bc238xMmo7DepjeGzA0zSn7hEL7hgdYGTcI}
app.jwt.expiration=86400000