server.port=8080

spring.application.name=api-gateway

# ===== Register Service - public =====
spring.cloud.gateway.routes[0].id=register-service
spring.cloud.gateway.routes[0].uri=http://register-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/register/**
spring.cloud.gateway.routes[0].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[0].filters[0].args.secured=false

# ===== Login Service - public =====
spring.cloud.gateway.routes[1].id=login-service
spring.cloud.gateway.routes[1].uri=http://login-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/login/**
spring.cloud.gateway.routes[1].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[1].filters[0].args.secured=false

# ===== Protected routes =====
spring.cloud.gateway.routes[2].id=login-service-protected
spring.cloud.gateway.routes[2].uri=http://login-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[2].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[2].filters[0].args.secured=true

# ===== JWT =====
app.jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenMustBe32Chars}